services:
  eureka-discovery-service:
    container_name: eureka-discovery-service
    build:
      context: ./eureka-discovery-service
    ports:
      - "8761:8761"

  resource-processor:
    container_name: resource-processor
    build:
      context: ./resource-processor
    ports:
      - "8086:8086"
    environment:
      EUREKA_CLIENT_SERVICE_URL: ${EUREKA_CLIENT_SERVICE_URL}

  resource-service:
    container_name: resource-service
    build:
      context: ./resource-service
    ports:
      - "8081:8081"
    depends_on:
      - resource-db
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL: ${EUREKA_CLIENT_SERVICE_URL}
      LOCALSTACK_SERVICE_URL: ${LOCALSTACK_SERVICE_URL}

  resource-db:
    container_name: resource-db
    image: postgres:17-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: ${RESOURCE_DB_DATABASE}
      POSTGRES_USER: ${RESOURCE_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d

  song-service:
    build:
      context: ./song-service
    ports:
      - "8082-8083:8082"
    depends_on:
      - song-db
    deploy:
      replicas: 2
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL: ${EUREKA_CLIENT_SERVICE_URL}

  song-db:
    container_name: song-db
    image: postgres:17-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: ${SONG_DB_DATABASE}
      POSTGRES_USER: ${SONG_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SONG_DB_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d

  localstack:
    container_name: localstack-service
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"