# All configurations are fetched from Config Server
# This file can be left empty or contain only bootstrap-level configs
spring.application.name=eureka-discovery-service

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF