spring.application.name=resource-processor
server.port=8086

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
resource.kafka.topic=${RESOURCE_CREATED_TOPIC:resource-created}
resource.kafka.groupId=resource-processor

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
eureka.instance.home-page-url-path=/resource-processor

song.service.application.name=song-service
resource.service.application.name=resource-service