spring.application.name=resource-service

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Song service integration url
song.service.url=${SONG_SERVICE_URL:http://localhost:8082/songs}

# Hibernate (turning off for transition to a containerized database setup)
spring.jpa.hibernate.ddl-auto=none

# Limit consuming file/request size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Exclude stack trace for error responses
server.error.include-stacktrace=on_param
server.error.whitelabel.enabled=false
server.error.include-message=on_param

server.port=8081

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
song.service.application.name=song-service